In [9]:
import pandas as pd
df=pd.read_csv("C:/Users/user/Downloads/archive (10)/netflix_titles.csv")

In [10]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [11]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [12]:
df.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [13]:
df.shape

(8807, 12)

In [14]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

In [15]:
df.dtypes

show_id           str
type              str
title             str
director          str
cast              str
country           str
date_added        str
release_year    int64
rating            str
duration          str
listed_in         str
description       str
dtype: object

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

In [17]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [18]:
df["release_year"].mean()

np.float64(2014.1801975701146)

In [19]:
df["release_year"].mode()

0    2018
Name: release_year, dtype: int64

In [20]:
df["release_year"].median()

np.float64(2017.0)

In [21]:
df["release_year"].var()

np.float64(77.78026646107516)

In [22]:
df["release_year"].std()

np.float64(8.819312130833966)

In [23]:
df["release_year"].min()

np.int64(1925)

In [24]:
df["release_year"].max()

np.int64(2021)

In [28]:
df["country"].unique()

<StringArray>
[                                                        'United States',
                                                          'South Africa',
                                                                     nan,
                                                                 'India',
 'United States, Ghana, Burkina Faso, United Kingdom, Germany, Ethiopia',
                                                        'United Kingdom',
                                               'Germany, Czech Republic',
                                                                'Mexico',
                                                                'Turkey',
                                                             'Australia',
 ...
                        'Germany, United States, United Kingdom, Canada',
          'Canada, India, Thailand, United States, United Arab Emirates',
                             'United States, East Germany, West Germany',
                            'France, Netherlands, South Africa, Finland',
                                         'Egypt, Austria, United States',
                                                         'Russia, Spain',
                                 'Croatia, Slovenia, Serbia, Montenegro',
                                                         'Japan, Canada',
                         'United States, France, South Korea, Indonesia',
                                          'United Arab Emirates, Jordan']
Length: 749, dtype: str

In [26]:
df["release_year"].count()

np.int64(8807)

In [29]:
df["country"].nunique()

748

In [30]:
df["country"].value_counts()

country
United States                                    2818
India                                             972
United Kingdom                                    419
Japan                                             245
South Korea                                       199
                                                 ...
Russia, Spain                                       1
Croatia, Slovenia, Serbia, Montenegro               1
Japan, Canada                                       1
United States, France, South Korea, Indonesia       1
United Arab Emirates, Jordan                        1
Name: count, Length: 748, dtype: int64

In [31]:
df.isnull()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,False,False,False,False,True,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False,False,False,False
2,False,False,False,False,False,True,False,False,False,False,False,False
3,False,False,False,True,True,True,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,False,False,False,False,False,False,False,False,False,False,False,False
8803,False,False,False,True,True,True,False,False,False,False,False,False
8804,False,False,False,False,False,False,False,False,False,False,False,False
8805,False,False,False,False,False,False,False,False,False,False,False,False
8806,False,False,False,False,False,False,False,False,False,False,False,False

In [32]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [33]:
df.isnull().mean()*100

show_id          0.000000
type             0.000000
title            0.000000
director        29.908028
cast             9.367549
country          9.435676
date_added       0.113546
release_year     0.000000
rating           0.045418
duration         0.034064
listed_in        0.000000
description      0.000000
dtype: float64

In [34]:
df.dropna()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,"September 21, 2021",1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...
...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [35]:
df.fillna(0)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,0,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,0,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",0,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,0,0,0,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,0,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,0,0,0,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [36]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
8802    False
8803    False
8804    False
8805    False
8806    False
Length: 8807, dtype: bool

In [37]:
df.duplicated().sum()

np.int64(0)

In [38]:
df.drop_duplicates()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [39]:
df["type"]

0         Movie
1       TV Show
2       TV Show
3       TV Show
4       TV Show
         ...
8802      Movie
8803    TV Show
8804      Movie
8805      Movie
8806      Movie
Name: type, Length: 8807, dtype: str

In [40]:
df[["type","duration"]]

         type   duration
0       Movie     90 min
1     TV Show  2 Seasons
2     TV Show   1 Season
3     TV Show   1 Season
4     TV Show  2 Seasons
...       ...        ...
8802    Movie    158 min
8803  TV Show  2 Seasons
8804    Movie     88 min
8805    Movie     88 min
8806    Movie    111 min

[8807 rows x 2 columns]

In [41]:
df.iloc[0:10]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...

In [42]:
df[df["release_year"] > 2015]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8787,s8788,Movie,You Can’t Fight Christmas,Kenny Young,"Brely Evans, Andra Fuller, Persia White, Porsc...",United States,"December 19, 2017",2017,TV-PG,85 min,"Comedies, Romantic Movies",After stepping in to revitalize his family's h...
8794,s8795,Movie,اشتباك,Mohamed Diab,"Nelly Karim, Hany Adel, Tarek Abdel Aziz, Ahme...","Egypt, France","October 11, 2018",2016,TV-14,98 min,"Dramas, Independent Movies, International Movies",Amid the tumult following Egyptian President M...
8796,s8797,TV Show,Yunus Emre,NaN,"Gökhan Atalay, Payidar Tüfekçioglu, Baran Akbu...",Turkey,"January 17, 2017",2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas","During the Mongol invasions, Yunus Emre leaves..."
8797,s8798,TV Show,Zak Storm,NaN,"Michael Johnston, Jessica Gee-George, Christin...","United States, France, South Korea, Indonesia","September 13, 2018",2016,TV-Y7,3 Seasons,Kids' TV,Teen surfer Zak Storm is mysteriously transpor...
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."

In [43]:
df.sort_values("duration")

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8216,s8217,TV Show,The Bomb Squad,NaN,Christopher Eccleston,United Kingdom,"February 1, 2019",2011,TV-MA,1 Season,"British TV Shows, Docuseries",This documentary follows British bomb disposal...
5392,s5393,TV Show,Barbie Life in the Dreamhouse,NaN,"Kate Higgins, Sean Hankinson, Haviland Stillwe...","United States, Canada","July 1, 2017",2012,TV-Y,1 Season,"Kids' TV, TV Comedies",Join blond icon Barbie and her fabulous friend...
3794,s3795,TV Show,Historical Roasts,NaN,"Jeff Ross, Bob Saget, James Adomian, Rachel Fe...",United States,"May 27, 2019",2019,TV-MA,1 Season,"Stand-Up Comedy & Talk Shows, TV Comedies","""Roastmaster General"" Jeff Ross and a slew of ..."
1593,s1594,TV Show,Kings of Jo'Burg,NaN,"Shona Ferguson, Zolisa Xaluva, Tsholofelo Mats...",South Africa,"December 4, 2020",2020,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",The Masire brothers rule Johannesburg's crimin...
5393,s5394,TV Show,Breakout,NaN,"Jeanette Aw, Elvin Ng, Zhou Ying, Christopher ...",NaN,"July 1, 2017",2010,TV-14,1 Season,"International TV Shows, TV Dramas",After losing her family in a suspicious car cr...
...,...,...,...,...,...,...,...,...,...,...,...,...
5976,s5977,Movie,Çok Filim Hareketler Bunlar,Ozan Açıktan,"Ayça Erturan, Aydan Taş, Ayşegül Akdemir, Burc...",Turkey,"March 10, 2017",2010,TV-MA,99 min,"Comedies, International Movies",Vignettes of the summer holidays follow vacati...
4401,s4402,Movie,"All's Well, End's Well (2009)",Vincent Kok,"Louis Koo, Sandra Ng Kwan Yue, Raymond Wong, R...",Hong Kong,"November 9, 2018",2009,TV-14,99 min,"Comedies, International Movies, Romantic Movies",Bound by a family rule that forbids him from m...
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...

In [44]:
df.rename(columns={"rating":"Ratings"})

,show_id,type,title,director,cast,country,date_added,release_year,Ratings,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [45]:
df["increase"] = df["duration"]*0.10

TypeError: can't multiply sequence by non-int of type 'float'

In [47]:
import pandas as pd
df=pd.read_csv("C:/Users/user/Downloads/student performance dataset 1/student_data.csv")
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [51]:
import pandas as pd
df=pd.read_csv("C:/Users/user/Downloads/archive (11)/Employee.csv")
df

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
...,...,...,...,...,...,...,...,...,...
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [52]:
import pandas as pd
df=pd.read_csv("C:/Users/user/Downloads/archive (12)/employee_salary_dataset.csv")
df

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450
5,6,Employee_6,Finance,3,High School,50,Male,Mumbai,65818
6,7,Employee_7,IT,14,PhD,57,Male,Mumbai,70525
7,8,Employee_8,IT,17,PhD,34,Female,Bangalore,44830
8,9,Employee_9,IT,4,Bachelor,53,Male,Hyderabad,42429
9,10,Employee_10,Operations,18,High School,28,Male,Mumbai,31893
10,11,Employee_11,Marketing,8,PhD,43,Male,Delhi,141381
11,12,Employee_12,IT,4,Master,49,Female,Hyderabad,104909
12,13,Employee_13,Operations,2,Master,23,Female,Hyderabad,72333
13,14,Employee_14,Finance,6,Bachelor,27,Male,Delhi,28436
14,15,Employee_15,Marketing,10,PhD,49,Female,Mumbai,99290
15,16,Employee_16,Finance,4,High School,49,Female,Delhi,101213
16,17,Employee_17,Marketing,18,Master,41,Female,Hyderabad,30895
17,18,Employee_18,Operations,12,PhD,51,Female,Chennai,44738
18,19,Employee_19,HR,2,PhD,32,Male,Chennai,55746
19,20,Employee_20,Marketing,10,Bachelor,49,Male,Bangalore,74377
20,21,Employee_21,Finance,4,Master,46,Female,Delhi,73404
21,22,Employee_22,Operations,14,Master,54,Female,Delhi,79045
22,23,Employee_23,Marketing,16,High School,22,Male,Bangalore,122888
23,24,Employee_24,HR,15,Master,48,Male,Bangalore,64790
24,25,Employee_25,HR,8,High School,34,Female,Bangalore,132455
25,26,Employee_26,IT,14,Master,24,Male,Hyderabad,30600
26,27,Employee_27,IT,8,Bachelor,27,Female,Delhi,119660
27,28,Employee_28,Finance,16,Master,29,Female,Hyderabad,118179
28,29,Employee_29,Marketing,13,High School,48,Male,Bangalore,65764
29,30,Employee_30,Marketing,18,High School,30,Male,Delhi,99543
30,31,Employee_31,IT,15,Bachelor,54,Female,Hyderabad,70714
31,32,Employee_32,Marketing,13,Master,45,Female,Hyderabad,81835
32,33,Employee_33,Marketing,9,Master,36,Male,Bangalore,127946
33,34,Employee_34,HR,15,Bachelor,53,Female,Delhi,134616
34,35,Employee_35,IT,13,Master,53,Male,Bangalore,130983
35,36,Employee_36,Operations,1,Master,45,Female,Delhi,98744
36,37,Employee_37,IT,7,High School,33,Male,Chennai,81491
37,38,Employee_38,Operations,9,Master,23,Male,Mumbai,149123
38,39,Employee_39,HR,1,Master,24,Male,Mumbai,43589
39,40,Employee_40,Finance,12,Bachelor,38,Female,Mumbai,68484
40,41,Employee_41,Marketing,8,Bachelor,23,Female,Bangalore,107989
41,42,Employee_42,HR,11,PhD,23,Male,Chennai,61212
42,43,Employee_43,Marketing,19,High School,49,Female,Delhi,68525
43,44,Employee_44,Finance,17,Master,44,Male,Hyderabad,72202
44,45,Employee_45,Finance,8,Master,53,Male,Delhi,57635
45,46,Employee_46,HR,3,PhD,54,Female,Hyderabad,88208
46,47,Employee_47,Finance,3,Master,22,Female,Delhi,58828
47,48,Employee_48,Operations,1,High School,40,Male,Chennai,43711
48,49,Employee_49,Finance,5,PhD,23,Female,Hyderabad,28420
49,50,Employee_50,Marketing,10,High School,47,Female,Bangalore,121752

In [56]:
df["Bonus"] = df["Monthly_Salary"]*0.10
df

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary,Bonus
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416,11141.6
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271,9527.1
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064,6906.4
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091,9509.1
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450,13245.0
5,6,Employee_6,Finance,3,High School,50,Male,Mumbai,65818,6581.8
6,7,Employee_7,IT,14,PhD,57,Male,Mumbai,70525,7052.5
7,8,Employee_8,IT,17,PhD,34,Female,Bangalore,44830,4483.0
8,9,Employee_9,IT,4,Bachelor,53,Male,Hyderabad,42429,4242.9
9,10,Employee_10,Operations,18,High School,28,Male,Mumbai,31893,3189.3
10,11,Employee_11,Marketing,8,PhD,43,Male,Delhi,141381,14138.1
11,12,Employee_12,IT,4,Master,49,Female,Hyderabad,104909,10490.9
12,13,Employee_13,Operations,2,Master,23,Female,Hyderabad,72333,7233.3
13,14,Employee_14,Finance,6,Bachelor,27,Male,Delhi,28436,2843.6
14,15,Employee_15,Marketing,10,PhD,49,Female,Mumbai,99290,9929.0
15,16,Employee_16,Finance,4,High School,49,Female,Delhi,101213,10121.3
16,17,Employee_17,Marketing,18,Master,41,Female,Hyderabad,30895,3089.5
17,18,Employee_18,Operations,12,PhD,51,Female,Chennai,44738,4473.8
18,19,Employee_19,HR,2,PhD,32,Male,Chennai,55746,5574.6
19,20,Employee_20,Marketing,10,Bachelor,49,Male,Bangalore,74377,7437.7
20,21,Employee_21,Finance,4,Master,46,Female,Delhi,73404,7340.4
21,22,Employee_22,Operations,14,Master,54,Female,Delhi,79045,7904.5
22,23,Employee_23,Marketing,16,High School,22,Male,Bangalore,122888,12288.8
23,24,Employee_24,HR,15,Master,48,Male,Bangalore,64790,6479.0
24,25,Employee_25,HR,8,High School,34,Female,Bangalore,132455,13245.5
25,26,Employee_26,IT,14,Master,24,Male,Hyderabad,30600,3060.0
26,27,Employee_27,IT,8,Bachelor,27,Female,Delhi,119660,11966.0
27,28,Employee_28,Finance,16,Master,29,Female,Hyderabad,118179,11817.9
28,29,Employee_29,Marketing,13,High School,48,Male,Bangalore,65764,6576.4
29,30,Employee_30,Marketing,18,High School,30,Male,Delhi,99543,9954.3
30,31,Employee_31,IT,15,Bachelor,54,Female,Hyderabad,70714,7071.4
31,32,Employee_32,Marketing,13,Master,45,Female,Hyderabad,81835,8183.5
32,33,Employee_33,Marketing,9,Master,36,Male,Bangalore,127946,12794.6
33,34,Employee_34,HR,15,Bachelor,53,Female,Delhi,134616,13461.6
34,35,Employee_35,IT,13,Master,53,Male,Bangalore,130983,13098.3
35,36,Employee_36,Operations,1,Master,45,Female,Delhi,98744,9874.4
36,37,Employee_37,IT,7,High School,33,Male,Chennai,81491,8149.1
37,38,Employee_38,Operations,9,Master,23,Male,Mumbai,149123,14912.3
38,39,Employee_39,HR,1,Master,24,Male,Mumbai,43589,4358.9
39,40,Employee_40,Finance,12,Bachelor,38,Female,Mumbai,68484,6848.4
40,41,Employee_41,Marketing,8,Bachelor,23,Female,Bangalore,107989,10798.9
41,42,Employee_42,HR,11,PhD,23,Male,Chennai,61212,6121.2
42,43,Employee_43,Marketing,19,High School,49,Female,Delhi,68525,6852.5
43,44,Employee_44,Finance,17,Master,44,Male,Hyderabad,72202,7220.2
44,45,Employee_45,Finance,8,Master,53,Male,Delhi,57635,5763.5
45,46,Employee_46,HR,3,PhD,54,Female,Hyderabad,88208,8820.8
46,47,Employee_47,Finance,3,Master,22,Female,Delhi,58828,5882.8
47,48,Employee_48,Operations,1,High School,40,Male,Chennai,43711,4371.1
48,49,Employee_49,Finance,5,PhD,23,Female,Hyderabad,28420,2842.0
49,50,Employee_50,Marketing,10,High School,47,Female,Bangalore,121752,12175.2

In [57]:
df.drop("Bonus", axis=1)

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450
5,6,Employee_6,Finance,3,High School,50,Male,Mumbai,65818
6,7,Employee_7,IT,14,PhD,57,Male,Mumbai,70525
7,8,Employee_8,IT,17,PhD,34,Female,Bangalore,44830
8,9,Employee_9,IT,4,Bachelor,53,Male,Hyderabad,42429
9,10,Employee_10,Operations,18,High School,28,Male,Mumbai,31893
10,11,Employee_11,Marketing,8,PhD,43,Male,Delhi,141381
11,12,Employee_12,IT,4,Master,49,Female,Hyderabad,104909
12,13,Employee_13,Operations,2,Master,23,Female,Hyderabad,72333
13,14,Employee_14,Finance,6,Bachelor,27,Male,Delhi,28436
14,15,Employee_15,Marketing,10,PhD,49,Female,Mumbai,99290
15,16,Employee_16,Finance,4,High School,49,Female,Delhi,101213
16,17,Employee_17,Marketing,18,Master,41,Female,Hyderabad,30895
17,18,Employee_18,Operations,12,PhD,51,Female,Chennai,44738
18,19,Employee_19,HR,2,PhD,32,Male,Chennai,55746
19,20,Employee_20,Marketing,10,Bachelor,49,Male,Bangalore,74377
20,21,Employee_21,Finance,4,Master,46,Female,Delhi,73404
21,22,Employee_22,Operations,14,Master,54,Female,Delhi,79045
22,23,Employee_23,Marketing,16,High School,22,Male,Bangalore,122888
23,24,Employee_24,HR,15,Master,48,Male,Bangalore,64790
24,25,Employee_25,HR,8,High School,34,Female,Bangalore,132455
25,26,Employee_26,IT,14,Master,24,Male,Hyderabad,30600
26,27,Employee_27,IT,8,Bachelor,27,Female,Delhi,119660
27,28,Employee_28,Finance,16,Master,29,Female,Hyderabad,118179
28,29,Employee_29,Marketing,13,High School,48,Male,Bangalore,65764
29,30,Employee_30,Marketing,18,High School,30,Male,Delhi,99543
30,31,Employee_31,IT,15,Bachelor,54,Female,Hyderabad,70714
31,32,Employee_32,Marketing,13,Master,45,Female,Hyderabad,81835
32,33,Employee_33,Marketing,9,Master,36,Male,Bangalore,127946
33,34,Employee_34,HR,15,Bachelor,53,Female,Delhi,134616
34,35,Employee_35,IT,13,Master,53,Male,Bangalore,130983
35,36,Employee_36,Operations,1,Master,45,Female,Delhi,98744
36,37,Employee_37,IT,7,High School,33,Male,Chennai,81491
37,38,Employee_38,Operations,9,Master,23,Male,Mumbai,149123
38,39,Employee_39,HR,1,Master,24,Male,Mumbai,43589
39,40,Employee_40,Finance,12,Bachelor,38,Female,Mumbai,68484
40,41,Employee_41,Marketing,8,Bachelor,23,Female,Bangalore,107989
41,42,Employee_42,HR,11,PhD,23,Male,Chennai,61212
42,43,Employee_43,Marketing,19,High School,49,Female,Delhi,68525
43,44,Employee_44,Finance,17,Master,44,Male,Hyderabad,72202
44,45,Employee_45,Finance,8,Master,53,Male,Delhi,57635
45,46,Employee_46,HR,3,PhD,54,Female,Hyderabad,88208
46,47,Employee_47,Finance,3,Master,22,Female,Delhi,58828
47,48,Employee_48,Operations,1,High School,40,Male,Chennai,43711
48,49,Employee_49,Finance,5,PhD,23,Female,Hyderabad,28420
49,50,Employee_50,Marketing,10,High School,47,Female,Bangalore,121752

In [60]:
df.groupby("Department")

In [61]:
df.groupby("Department")["Monthly_Salary"].mean()

Department
Finance       67261.900000
HR            82945.142857
IT            76520.500000
Marketing     96430.846154
Operations    84239.900000
Name: Monthly_Salary, dtype: float64

In [63]:
df1=pd.read_csv("C:/Users/user/Downloads/archive (12)/employee_salary_dataset.csv")
df2=pd.read_csv("C:/Users/user/Downloads/archive (10)/netflix_titles.csv")
pd.concat([df1,df2])

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary,show_id,...,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,1.0,Employee_1,Marketing,15.0,Master,53.0,Female,Delhi,111416.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Employee_2,Operations,7.0,Bachelor,25.0,Female,Bangalore,95271.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Employee_3,IT,12.0,High School,51.0,Female,Hyderabad,69064.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Employee_4,Operations,8.0,PhD,44.0,Male,Delhi,95091.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,Employee_5,Operations,15.0,Master,36.0,Female,Delhi,132450.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s8803,...,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007.0,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s8804,...,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018.0,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s8805,...,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009.0,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s8806,...,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006.0,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,s8807,...,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015.0,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...