In [8]:
import pandas as pd
df=pd.read_csv("C:/Users/User/Downloads/archive(5)/Heart_disease_statlog.csv")
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,70,1,3,130,322,0,2,109,0,2.4,1,3,1,1
1,67,0,2,115,564,0,2,160,0,1.6,1,0,3,0
2,57,1,1,124,261,0,0,141,0,0.3,0,0,3,1
3,64,1,3,128,263,0,0,105,1,0.2,1,1,3,0
4,74,0,1,120,269,0,2,121,1,0.2,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,52,1,2,172,199,1,0,162,0,0.5,0,0,3,0
266,44,1,1,120,263,0,0,173,0,0.0,0,0,3,0
267,56,0,1,140,294,0,2,153,0,1.3,1,0,1,0
268,57,1,3,140,192,0,0,148,0,0.4,1,0,2,0
269,67,1,3,160,286,0,2,108,1,1.5,1,3,1,1

In [9]:
print(df.isnull())

       age    sex     cp  trestbps   chol    fbs  restecg  thalach  exang  \
0    False  False  False     False  False  False    False    False  False
1    False  False  False     False  False  False    False    False  False
2    False  False  False     False  False  False    False    False  False
3    False  False  False     False  False  False    False    False  False
4    False  False  False     False  False  False    False    False  False
..     ...    ...    ...       ...    ...    ...      ...      ...    ...
265  False  False  False     False  False  False    False    False  False
266  False  False  False     False  False  False    False    False  False
267  False  False  False     False  False  False    False    False  False
268  False  False  False     False  False  False    False    False  False
269  False  False  False     False  False  False    False    False  False

     oldpeak  slope     ca   thal  target
0      False  False  False  False   False
1      False  False  False  False   False
2      False  False  False  False   False
3      False  False  False  False   False
4      False  False  False  False   False
..       ...    ...    ...    ...     ...
265    False  False  False  False   False
266    False  False  False  False   False
267    False  False  False  False   False
268    False  False  False  False   False
269    False  False  False  False   False

[270 rows x 14 columns]

In [10]:
print(df.isnull().sum())

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [14]:
df['age'] = df['age'].fillna(df['age'].mean())
print(df)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     70    1   3       130   322    0        2      109      0      2.4
1     67    0   2       115   564    0        2      160      0      1.6
2     57    1   1       124   261    0        0      141      0      0.3
3     64    1   3       128   263    0        0      105      1      0.2
4     74    0   1       120   269    0        2      121      1      0.2
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
265   52    1   2       172   199    1        0      162      0      0.5
266   44    1   1       120   263    0        0      173      0      0.0
267   56    0   1       140   294    0        2      153      0      1.3
268   57    1   3       140   192    0        0      148      0      0.4
269   67    1   3       160   286    0        2      108      1      1.5

     slope  ca  thal  target
0        1   3     1       1
1        1   0     3       0
2        0   0     3       1
3        1   1     3       0
4        0   1     1       0
..     ...  ..   ...     ...
265      0   0     3       0
266      0   0     3       0
267      1   0     1       0
268      1   0     2       0
269      1   3     1       1

[270 rows x 14 columns]

In [16]:
print("Mean Age:", df['age'].mean())

Mean Age: 54.43333333333333

In [2]:
import pandas  as pd
data = {
    'Name': ['Anu', 'Ravi', 'Priya', 'Kiran', 'Meena', 'Arjun'],
    'Age': [21, 22, None, 23, 21, None],
    'Salary': [25000, None, 30000, 28000, None, 32000],
    'Department': ['CSE', 'ECE', 'CSE', None, 'ISE', 'ECE'],
    'City': ['Mysore', 'Bangalore', 'Mysore', 'Hubli', 'Bangalore', 'Mysore']
}
df = pd.DataFrame(data)
df['Salary'] = df['Salary'].fillna(df['Salary'].median())
print(df)

    Name   Age   Salary Department       City
0    Anu  21.0  25000.0        CSE     Mysore
1   Ravi  22.0  29000.0        ECE  Bangalore
2  Priya   NaN  30000.0        CSE     Mysore
3  Kiran  23.0  28000.0        NaN      Hubli
4  Meena  21.0  29000.0        ISE  Bangalore
5  Arjun   NaN  32000.0        ECE     Mysore

In [3]:
data = {
    'Student': ['Anu', 'Ravi', 'Priya', 'Kiran', 'Meena'],
    'Department': ['CSE', 'ECE', None, 'ISE', None]
}

df = pd.DataFrame(data)
print("Before Forward Fill:")
print(df)

df['Department'] = df['Department'].ffill()
print("\nAfter Forward Fill:")
print(df)

Before Forward Fill:
  Student Department
0     Anu        CSE
1    Ravi        ECE
2   Priya        NaN
3   Kiran        ISE
4   Meena        NaN

After Forward Fill:
  Student Department
0     Anu        CSE
1    Ravi        ECE
2   Priya        ECE
3   Kiran        ISE
4   Meena        ISE

In [4]:
from sklearn.preprocessing import LabelEncoder
data = {
    'Name': ['Anu', 'Ravi', 'Priya', 'Kiran'],
    'Department': ['CSE', 'ECE', 'ISE', 'CSE']
}
df = pd.DataFrame(data)
encoder = LabelEncoder()
df['Department_Encoded'] = encoder.fit_transform(df['Department'])
print(df)
print(encoder.classes_)

ModuleNotFoundError: No module named 'sklearn'

In [9]:
pip install sklearn

Collecting sklearn
  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.

  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [15 lines of output]
  The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
  rather than 'sklearn' for pip commands.

  Here is how to fix this error in the main use cases:
  - use 'pip install scikit-learn' rather than 'pip install sklearn'
  - replace 'sklearn' by 'scikit-learn' in your pip requirements files
    (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
  - if the 'sklearn' package is used by one of your dependencies,
    it would be great if you take some time to track which package uses
    'sklearn' instead of 'scikit-learn' and report it to their issue tracker
  - as a last resort, set the environment variable
    SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

  More information is available at
  https://github.com/scikit-learn/sklearn-pypi-package
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed to build 'sklearn' when getting requirements to build wheel

In [13]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.5.2)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in C:\Users\User\AppData\Local\Programs\Python\Python314\Lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Note: you may need to restart the kernel to use updated packages.

In [17]:
from sklearn.preprocessing import LabelEncoder
data = {
    'Name': ['Anu', 'Ravi', 'Priya', 'Kiran'],
    'Department': ['CSE', 'ECE', 'ISE', 'CSE']
}

df = pd.DataFrame(data)
encoder = LabelEncoder()
df['Department_Encoded'] = encoder.fit_transform(df['Department'])
print(df)
print(encoder.classes_)

    Name Department  Department_Encoded
0    Anu        CSE                   0
1   Ravi        ECE                   1
2  Priya        ISE                   2
3  Kiran        CSE                   0
['CSE' 'ECE' 'ISE']

In [18]:
import pandas as pd
data = {
    'Name': ['Anu', 'Ravi', 'Priya', 'Kiran'],
    'Department': ['CSE', 'ECE', 'ISE', 'CSE']
}
df = pd.DataFrame(data)
encoded_df = pd.get_dummies(df, columns=['Department'])
print(encoded_df)

    Name  Department_CSE  Department_ECE  Department_ISE
0    Anu            True           False           False
1   Ravi           False            True           False
2  Priya           False           False            True
3  Kiran            True           False           False

In [19]:
encoded_df = pd.get_dummies(
    df,
    columns=['Department'],
    dtype=int
)
print(encoded_df)

    Name  Department_CSE  Department_ECE  Department_ISE
0    Anu               1               0               0
1   Ravi               0               1               0
2  Priya               0               0               1
3  Kiran               1               0               0

In [21]:
import pandas as pd
df=pd.read_csv("C:/Users/User/Downloads/archive(6)/synthetic_dataset.csv")
df

     Category   Price    Rating         Stock  Discount
0         NaN  5548.0  1.870322           NaN       0.0
1         NaN  3045.0  4.757798           NaN      38.0
2         NaN  4004.0       NaN      In Stock       0.0
3         NaN  4808.0  1.492085           NaN      33.0
4         NaN  1817.0       NaN  Out of Stock      23.0
...       ...     ...       ...           ...       ...
4357      NaN  4436.0  4.728335           NaN      49.0
4358        B  6236.0       NaN  Out of Stock       4.0
4359      NaN  3283.0       NaN  Out of Stock       9.0
4360        D  2999.0  4.425995           NaN      40.0
4361      NaN     NaN  2.184471           NaN       0.0

[4362 rows x 5 columns]

In [22]:
from sklearn.preprocessing import LabelEncoder
df['Category'] = df['Category'].ffill()
encoder = LabelEncoder()
df['Category_Encoded'] = encoder.fit_transform(df['Category'])
print(df)
print(encoder.classes_)

     Category   Price    Rating         Stock  Discount  Category_Encoded
0         NaN  5548.0  1.870322           NaN       0.0                 4
1         NaN  3045.0  4.757798           NaN      38.0                 4
2         NaN  4004.0       NaN      In Stock       0.0                 4
3         NaN  4808.0  1.492085           NaN      33.0                 4
4         NaN  1817.0       NaN  Out of Stock      23.0                 4
...       ...     ...       ...           ...       ...               ...
4357        B  4436.0  4.728335           NaN      49.0                 1
4358        B  6236.0       NaN  Out of Stock       4.0                 1
4359        B  3283.0       NaN  Out of Stock       9.0                 1
4360        D  2999.0  4.425995           NaN      40.0                 3
4361        D     NaN  2.184471           NaN       0.0                 3

[4362 rows x 6 columns]
['A' 'B' 'C' 'D' nan]